### ISSUE TITLE
router failed in latest flutter

### ISSUE THREAD

**Issue by namiwang** [goposse/fluro#41]
I've got some code involving fluro which works fine until I upgrade flutter to `Flutter (Channel master, v0.2.3-pre.41, on Mac OS X 10.13.3 17D102, locale en-US)`

```
import 'package:flutter/material.dart';

import 'package:fluro/fluro.dart';

void main() => runApp(new MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {

    final router = new Router();
    router.define("/users/:id", handler: new Handler(handlerFunc: (BuildContext context, Map<String, dynamic> params) {
      return new PagesUser(userId: params["id"][0]);
    }));

    return new MaterialApp(
      title: 'title',
      initialRoute: 'users/a',
      onGenerateRoute: router.generator,
    );
  }
}
```

will produce
```

I/flutter (15772): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (15772): The following assertion was thrown while handling a gesture:
I/flutter (15772): type 'PageRouteBuilder' is not a subtype of type 'Route<Null>' where
I/flutter (15772):   PageRouteBuilder is from package:flutter/src/widgets/pages.dart
I/flutter (15772):   Route is from package:flutter/src/widgets/navigator.dart
I/flutter (15772):   Null is from dart:core
I/flutter (15772):
I/flutter (15772): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (15772): more information in this error message to help you determine and fix the underlying cause.
I/flutter (15772): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (15772):   https://github.com/flutter/flutter/issues/new
I/flutter (15772):
I/flutter (15772): When the exception was thrown, this was the stack:
I/flutter (15772): #0      Router.generator (file:///Users/nano/.pub-cache/hosted/pub.dartlang.org/fluro-1.3.0/lib/src/router.dart:165:18)
I/flutter (15772): #1      _MaterialAppState._onGenerateRoute (package:flutter/src/material/app.dart:621:21)
I/flutter (15772): #2      NavigatorState._routeNamed (package:flutter/src/widgets/navigator.dart:857:35)
I/flutter (15772): #3      NavigatorState.pushNamed (package:flutter/src/widgets/navigator.dart:902:17)
I/flutter (15772): #4      StatusItem._buildStatusTitle.<anonymous closure> (file:///Users/nano/workspace/uraaka/app/lib/views/statuses/item.dart:51:41)
I/flutter (15772): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter (15772): #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
I/flutter (15772): #7      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:123:7)
I/flutter (15772): #8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
I/flutter (15772): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
I/flutter (15772): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
I/flutter (15772): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
I/flutter (15772): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
I/flutter (15772): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
I/flutter (15772): #14     _invoke1 (dart:ui/hooks.dart:134:13)
I/flutter (15772): #15     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
```

Still not sure if this is an issue of fluro or flutter.

**Comment by namiwang** [comment]
I believe this is related to dart 2 type checking.

**Comment by lukef** [comment]
Fixed in #43. Thanks @jalpedersen  !!!!!

**Comment by namiwang** [comment]
@lukef Hi, we're still getting the same error in the latest flutter and fluro 1.3.1, with the same code
